version: '2'
services:
 web:
   image: marvambass/piwik:3.0.3
   restart: always
   depends_on:
     - db
   volumes:
    - "${NGINX_EXTERNAL_PATH}:/etc/nginx/external"
   env_file:
    - web-default.env
   ports:
    - "8180:80"
   links:
    - db:db
 db:
  image: marvambass/mysql
  restart: always
  volumes:
   - "${MYSQL_DATA_PATH}:/var/lib/mysql"
   - "${MYSQL_BACKUP_PATH}:/var/mysql-backup"
   - "${MYSQL_LOG_PATH}:/var/log/mysql"
  env_file:
   - db-default.env