version: '2'
services:
 web:
   image: marvambass/piwik:3.0.3
   restart: always
   depends_on:
     - db
   volumes:
    - ./external:/etc/nginx/external
   env_file:
    - web-default.env
   ports:
    - "8180:80"
   links:
    - db:db
 db:
  image: marvambass/mysql
  restart: always
  volumes:
   - ./mysql/data/:/var/lib/mysql
   - ./mysql/backup/:/var/mysql-backup
   - ./mysql/log:/var/log/mysql
  env_file:
   - db-default.env